apiVersion: v1
kind: Pod
metadata:
  name: firstpod
  namespace: default
spec:
  containers:
  - name: firstcont
    image: nginx
  - name: secondcont
    image: httpd
    savasvfsvfsvfvfdvf
    davfvfvfvfvfdvfdvf
